## YAML Template.
---
driverDB: com.mysql.jdbc.Driver
urlDB: jdbc:mysql://db4free.net:3306/ornitorrinco?useSSL=false
userDB: ornitorrinco
passDB: nohay2sin3
mailFrom: alumno1@iesquevedo.es
smtpServer: smtp.gmail.com
smtpPort: 587
mailPass: alumnodam2
##passDB: clasesdaw