## YAML Template.
---
driverDB: org.hsqldb.jdbc.JDBCDriver
urlDB: jdbc:hsqldb:mem:instituto
userDB: ornitorrinco
passDB: nohay2sin3
mailFrom: alumno1@iesquevedo.es
smtpServer: smtp.gmail.com
smtpPort: 587
mailPass: alumnodam2
##passDB: clasesdaw